In [17]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score,accuracy_score,confusion_matrix,recall_score


In [8]:
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [9]:
X = df.iloc[:,0:30]
y = df.iloc[:, 30]
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 4)

In [14]:
std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test  = std.fit_transform(X_test)

# KNN

In [15]:
kn = KNeighborsClassifier(n_neighbors=9,metric='euclidean')
kn.fit(X_train,y_train)
y_pred = kn.predict(X_test)

In [19]:
# Metrics
print("accuracy_score:",accuracy_score(y_pred,y_test))
print("precision_score:",precision_score(y_pred,y_test))
print("recall_score:",recall_score(y_pred,y_test))
confusion_matrix(y_pred,y_test)


accuracy_score: 0.9736842105263158
precision_score: 0.975
recall_score: 0.9873417721518988


array([[33,  2],
       [ 1, 78]])

# Decision Tree

In [20]:
dt = DecisionTreeClassifier(criterion='entropy',splitter='best',max_depth=5,max_leaf_nodes=5)
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)

In [21]:
print("accuracy_score:",accuracy_score(y_pred,y_test))
print("precision_score:",precision_score(y_pred,y_test))
print("recall_score:",recall_score(y_pred,y_test))
confusion_matrix(y_pred,y_test)

accuracy_score: 0.9035087719298246
precision_score: 0.9125
recall_score: 0.948051948051948


array([[30,  7],
       [ 4, 73]])

# Naive Bayes

In [22]:
nvb = GaussianNB()
nvb.fit(X_train,y_train)
y_pred = nvb.predict(X_test)

In [23]:
print("accuracy_score:",accuracy_score(y_pred,y_test))
print("precision_score:",precision_score(y_pred,y_test))
print("recall_score:",recall_score(y_pred,y_test))
confusion_matrix(y_pred,y_test)

accuracy_score: 0.9210526315789473
precision_score: 0.9125
recall_score: 0.9733333333333334


array([[32,  7],
       [ 2, 73]])